export const tweetsData = [   
  {
      handle: `@clauchakimaki 💎`,
      profilePic: `imagenes/clau.jpg`,
      likes: 27,
      retweets: 10,
      tweetText: `La mayor exportación de Australia son los boomerangs. También son la mayor importación.`,
      replies: [],
      isLiked: false,
      isRetweeted: false,
      isReplyVisible: false,
      canDelete: false,
      uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
  },    
  {
      handle: `@poposlavski 🫶`,
      profilePic: `imagenes/popo.jpg`,
      likes: 650,
      retweets: 34,
      tweetText: `Pepito, sal del coche y mira si funciona el intermitente... <br> <br> Ahora sí, ahora no, ahora sí, ahora no, ahora sí, ahora no…`,
      replies: [
                {
              handle: `@clauchakimaki 💎`,
              profilePic: `imagenes/clau.jpg`,
              tweetText: `Doctor, doctor, no sé lo que me pasa que cada vez que tomo café me duele el ojo derecho.<br> <br> ¿Has probado a sacar la cucharilla de la taza?`,
          },
                {
              handle: `@zorkabosnai 😎`,
              profilePic: `imagenes/zorka.jpg`,
              tweetText: `¿Qué pasa si se va la luz en una escuela privada? Que no se ve ni un pijo.`,
          },
      ],
      isLiked: false,
      isRetweeted: false,
      isReplyVisible: false,
      canDelete: false,
      uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
  },
      {
      handle: `@zorkabosnai 😎`,
      profilePic: `imagenes/zorka.jpg`,
      likes: 10,
      retweets: 3,
      tweetText: `Mamá, mamá, los spaghetti se están pegando. <br><br>  Déjalos que se maten.`,
      replies: [
          {
              handle: `@clauchakimaki 💎`,
              profilePic: `imagenes/clau.jpg`,
              tweetText: `Mi ordenador me gana al ajedrez, pero yo le gano boxeando.`,
          },
          {
              handle: `@poposlavski 🫶`,
              profilePic: `imagenes/popo.jpg`,
              tweetText: `Pero mira que te he dicho diez mil millones de veces que no exageres…`,
          },
      ],
      isLiked: false,
      isRetweeted: false,
      isReplyVisible: false,
      canDelete: false,
      uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
  },     
]